version: "3"
services:
   price_drop_bot:
      container_name: price_drop_bot
      build: ./
      image: result/latest
      environment:
         - BOT_TOKEN=${BOT_TOKEN}
         - MONGO_DB=${MONGO_DB}
         - MONGO_URL=${MONGO_URL}
         - MONGO_USERNAME=${MONGO_USERNAME}
         - MONGO_PASSWORD=${MONGO_PASSWORD}
